name: duolingo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #Firebase
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.3.0
  
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.3.0
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.7.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/appBar/crown_stroke.png
  - assets/images/appBar/flag.png
  - assets/images/appBar/navbar_diamont.png
  - assets/images/appBar/navbar_fire.png

  #welcome
  - assets/images/logo-with-duo.png
  #social
  - assets/images/social/facebook.png
  - assets/images/social/google.png
  #home_screen
  - assets/images/home_screen/lesson_egg.png
  - assets/images/home_screen/lesson_airplane.png
  - assets/images/home_screen/store_item_8.png
  - assets/images/home_screen/lesson_hamburger.png
  - assets/images/home_screen/lesson_baby.png
  - assets/images/home_screen/lesson_dialog.png
  - assets/images/home_screen/lesson_divisor_castle.png
  #floating_action_button
  - assets/images/floating_action_button/tab_training_selected.png
  - assets/images/floating_action_button/tab_training.png
  #bottom_navigation_bar
  - assets/images/bottom_navigation_bar/tab_lessons_selected.png
  - assets/images/bottom_navigation_bar/tab_lessons.png
  - assets/images/bottom_navigation_bar/tab_profile_selected.png
  - assets/images/bottom_navigation_bar/tab_profile.png
  - assets/images/bottom_navigation_bar/tab_ranking_selected.png
  - assets/images/bottom_navigation_bar/tab_ranking.png
  - assets/images/bottom_navigation_bar/tab_store_selected.png
  - assets/images/bottom_navigation_bar/tab_store.png
  - assets/images/bottom_navigation_bar/tab_stories_selected.png
  - assets/images/bottom_navigation_bar/tab_stories.png
  
  
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
